# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GameDBCore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxAlamofire'
  pod 'Swinject'

  # Pods for GameDBCore

  target 'GameDBCoreTests' do
    # Pods for testing
  end

end
